version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=@VSCode23
      - POSTGRES_USER=adminer
      - POSTGRES_DB=resume-generator

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
